# Generated by Django 5.1 on 2025-03-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_mage_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mage',
            new_name='image',
        ),
    ]
